### ISSUE TITLE
OpenAI/GooseAI does not seem to be working in production.

### ISSUE THREAD

**Issue by tayler6000** [robertskmiles/stampy#172]
OpenAI and GooseAI are both not working in production for some reason.

**Comment by tayler6000** [comment]
Everything is defaulting to Eliza

**Comment by robertskmiles** [comment]
Goose.ai is not indicating any problems on their dashboard. Though it does say I've used 0 tokens this month, which doesn't seem right

**Comment by tayler6000** [comment]
This seems to be an issue with our tokenizing. https://github.com/huggingface/tokenizers/issues/1074
