### ISSUE TITLE
Refactor string enumerables

### ISSUE THREAD

**Issue by UlisseMini** [robertskmiles/stampy#40]
The code is scattered with string enumerations like
```py
    def get_question(self, order_type="TOP"):
        """Pull the oldest question from the queue
        Returns False if the queue is empty, the question string otherwise"""
        comment = None
        if order_type == "RANDOM":
            comment = self.wiki.get_random_question()
        elif order_type == "TOP":
            comment = self.wiki.get_top_question()
        else:
            comment = self.wiki.get_latest_question()

        if not comment:
            return None

        # ...
```
This has the drawbacks that
1. It isn't immediately obvious what strings are valid
2. Functions are violating the single responsibility principle

These should be refactored into separate functions, for example this function should be refactored so it gets passed a comment
```py
def get_question(self, comment):
  ...
```
Then the function should be passed the comment
```py
comment = self.wiki.get_top_question()
self.get_question(comment)
```

In rare cases enumerables do make sense, in these cases use [enum classes](https://docs.python.org/3/library/enum.html)

TODO:
- [x] Find all occurrences of string enums and post them here as comments
- [x] Refactor them
- [x] Test that the code still runs (or run test suite it that gets fixed before this)

**Comment by MatthewBaggins** [comment]
The only examples I found is the one you posted and the following in `modules/stampcollection.py` (lines 46-49)


```
        if stamp_type == "stamp":
            vote_strength = self.red_stamp_value
        elif stamp_type == "goldstamp":
            vote_strength = self.gold_stamp_value

```

**Comment by MatthewBaggins** [comment]
Refactoring order type is easy. The case with `stampcollection.py` is more problematic because the method is called with `stamp_type` extracted from messages or `stamps.csv`. Optimally, I'd change it to a boolean `is_gold_stamp`

**Comment by MatthewBaggins** [comment]
I think this also qualifies as a string enum (`modules.py`, line 143), but this argument is never used, so maybe we should remove it, unless some functionality is planned for it?

```py
async def process_reaction_event(self, reaction, user, event_type="REACTION_ADD"):
```

**Comment by Aprillion** [comment]
no idea about future plans for more than one `event_type` myself.

since there is no code comment nor GitHub issue speaking about future plans for that argument, I would say that if no one replies by ~tomorrow about some urgent plans for this field in their PR "soon", we should delete it.

**Comment by robertskmiles** [comment]
Wait, it's never used? Possibly I'm not following what's being talked about here but doesn't `StampsModule` use it? It has to react differently to a stamp being added and a stamp being removed

**Comment by robertskmiles** [comment]
Upon closer inspection, the entire `process_reaction_event` method is essentially never used, only `StampsModule` uses it and that doesn't do anything except some logging. Everything that processes reacts uses `process_raw_reaction_event`, and that includes an event object that you can get the `event_type` string out of. (The string enum lives in the discord library itself I believe)

**Comment by MatthewBaggins** [comment]
So, should we remove `process_reaction_event` and rename `process_raw_reaction_event` to `process_reaction_event`?

**Comment by robertskmiles** [comment]
Yeah I think it makes sense to have only one method. As for the name though, it currently reflects the naming of the discord library's methods that trigger it: https://discordpy.readthedocs.io/en/stable/api.html#reactions so I think that makes sense.

`on_reaction_add` and `on_raw_reaction_add` are different library methods that do different things, and our naming should probably reflect that, although I'm not totally clear on what the distinction is or why we use the raw one, so that's worth looking into.
